version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - '5431:5431'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: