version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crosslink
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_crosslink:/var/lib/postgresql/data

volumes:
  postgres_data_crosslink: